name: Run OpenWrt on QEMU

on:
  workflow_dispatch:    # 手动触发

jobs:
  openwrt-qemu:
    runs-on: ubuntu-latest
    steps:
      - name: 安装 QEMU 虚拟机
        run: sudo apt update && sudo apt install -y qemu-system-aarch64

      - name: 下载 OpenWrt 固件
        run: |
          curl -o openwrt-armvirt-64-generic-ext4-rootfs.img.gz http://linzifu.xyz:8081/openwrt-armvirt-64-generic-ext4-rootfs.img.gz
          curl -o openwrt-armvirt-64-generic-kernel.bin.gz http://linzifu.xyz:8081/openwrt-armvirt-64-generic-kernel.bin.gz

      - name: 解压 OpenWrt 固件
        run: |
          gzip -d openwrt-armvirt-64-generic-ext4-rootfs.img.gz
          gzip -d openwrt-armvirt-64-generic-kernel.bin.gz

      - name: 运行 OpenWrt 虚拟机
        run: |
          qemu-system-aarch64 -M virt -m 1024m \
            -kernel openwrt-armvirt-64-generic-kernel.bin \
            -append "root=fe00" \
            -hda openwrt-armvirt-64-generic-ext4-rootfs.img \
            -no-reboot -nographic \
            -cpu cortex-a76 -smp 4 \
            -net nic -net user,id=wan,hostfwd=tcp::7080-:80,hostfwd=tcp::7022-:22

      - name: 动行 5 小时
        run: sleep 18000 
